Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import turtle
>>> turtle.down(50)
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    turtle.down(50)
TypeError: down() takes 0 positional arguments but 1 was given
>>> turtle.reset()
>>> turtle.down(50)
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    turtle.down(50)
TypeError: down() takes 0 positional arguments but 1 was given
>>> turtle.right()
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    turtle.right()
TypeError: right() missing 1 required positional argument: 'angle'
>>> turtle.right(90)
>>> turtle.goto(-100,0)
>>> turtle.undo()
>>> turtle.penup()
>>> turtle.goto(0,0)
>>> turtle.goto(-300,0)
>>> turtle.goto(0, 200)
>>> turtle.undo()
>>> turtle.goto(-300, 200)
>>> turtle.pendown()
>>> turtle.down(50)
Traceback (most recent call last):
  File "<pyshell#15>", line 1, in <module>
    turtle.down(50)
TypeError: down() takes 0 positional arguments but 1 was given
>>> turtle.forward(50)
>>> turtle.right(90)
>>> turtle.forward(50)
>>> turtle.right(180)
>>> turtle.forward(100)
>>> turtle.penup()
>>> turtle goto(-100, -50)
SyntaxError: invalid syntax
>>> turtle.right(180)
>>> turtle.forward(50)
>>> turtle.left(90)
>>> turtle.forward(40)
>>> turtle.pendown()
>>> turtle.circle(80)
>>> turtle.undo()
>>> turtle.penup()
>>> turtle.right(90)
>>> turtle.forward(30)
>>> turtile.left(90)
Traceback (most recent call last):
  File "<pyshell#33>", line 1, in <module>
    turtile.left(90)
NameError: name 'turtile' is not defined
>>> turtle.left(90)
>>> turtle.pendown()
>>> turtle.circle(10)
>>> turtle.undo()
>>> turtle.circle(40)
>>> turtle.undo()
>>> turtle.circle(20)
>>> turtle.undo()
>>> turtle.circle(30)
>>> turtle,penup()
Traceback (most recent call last):
  File "<pyshell#43>", line 1, in <module>
    turtle,penup()
NameError: name 'penup' is not defined
>>> turtle,penup()
Traceback (most recent call last):
  File "<pyshell#44>", line 1, in <module>
    turtle,penup()
NameError: name 'penup' is not defined
>>> turtle.penup()
>>> turtle.left(90)
>>> turtle.forward(100)
>>> turtle.forward(10)
>>> turtle.pendown()
>>> turtle.forward(10)
>>> turtle.undo()
>>> turtle.forward(20)
>>> turtle.undo()
>>> turtle.forward(30)
>>> turtle.back(30)
>>> turtle.right(90)
>>> turtle,forward(50)
Traceback (most recent call last):
  File "<pyshell#57>", line 1, in <module>
    turtle,forward(50)
NameError: name 'forward' is not defined
>>> turtle.forward(50)
>>> turtle.back(100)
>>> turtle.penup()
>>> turtle.goto(-300, -200)
>>> turtle.undo()
>>> turtle.goto(-200, -50)
>>> turtle.goto(-250, -25)
>>> turtle.goto(-270, -10)
>>> turtle.goto(-280, -5)
>>> turtle.goto(-290, -3)
>>> turtle.goto(-290, 0)
>>> turtle.goto(-290, 5)
>>> turtle.goto(-290, 10)
>>> turtle.goto(-290, 30)
>>> turtle.pendown()
>>> turtle.forward(30)
>>> turtle.left(90)
>>> turtle.forward(50)
>>> turtle.undo()
>>> turtle.undo()
>>> turtle.undo()
>>> turtle.penup()
>>> turtle.back(5)
>>> turtle.back(5)
>>> turtle.pendown()
>>> turtle.forward(40)
>>> turtle.left(90)
>>> turtle.forward(70)
>>> turtle.goto(0,0)
>>> turtle.undo()
>>> turtle.penup()
>>> turtle.goto(0, 50)
>>> turtle.back(50)
>>> turtle.back(30)
>>> turtle.back(30)
>>> turtle.up(100)
Traceback (most recent call last):
  File "<pyshell#93>", line 1, in <module>
    turtle.up(100)
TypeError: up() takes 0 positional arguments but 1 was given
>>> turtle.left(90)
>>> turtle.forward(100)
>>> turtle.forward(50)
>>> turtle.right(90)
>>> turtle.undo()
>>> turtle.back(10)
>>> turtle.back(10)
>>> turtle.right(90)
>>> turtle.forward(70)
>>> turtle.undo()
>>> turtle.pendown()
>>> turtle.forward(50)
>>> turtle.undo()
>>> turtle.forward(90)
>>> turtle.forward(90)
>>> turtle.undo()
>>> turtle.undo()
>>> turtle.forward(80)
>>> turtle.undo()
>>> turtle.forward(70)
>>> turtle.penup()
>>> turtle.goto(0, 0)
>>> turtle.goto(-20, 100)
>>> turtle.goto(-50, 150)
>>> turtle.goto(-50, 150)
>>> turtle.goto(-70, 150)
>>> turtle.goto(-100, 150)
>>> turtle.goto(-120, 150)
>>> turtle.pendown()
>>> turtle.forward(200)
>>> turtle.undo()
>>> turtle.forward(120)
>>> turtle.undo()
>>> turtle.forward(100)
>>> turtle.penup()
>>> turtule.goto(-70, 120)
Traceback (most recent call last):
  File "<pyshell#129>", line 1, in <module>
    turtule.goto(-70, 120)
NameError: name 'turtule' is not defined
>>> turtule.goto(-70,120)
Traceback (most recent call last):
  File "<pyshell#130>", line 1, in <module>
    turtule.goto(-70,120)
NameError: name 'turtule' is not defined
>>> turtle.goto(-70,120)
>>> turtle.back(20)
>>> turtle.forward(10)
>>> turtle.circle(30)
>>> turtle.right(90)
>>> turtle.undo()
>>> turtle.undo()
>>> turtle.undo()
>>> turtle.right(90)
>>> turtle.circle(20)
>>> turtle.undo()
>>> turtle.undo()
>>> turtle.undo()
>>> turtle.undo()
>>> turtle.rigth(120)
Traceback (most recent call last):
  File "<pyshell#145>", line 1, in <module>
    turtle.rigth(120)
AttributeError: module 'turtle' has no attribute 'rigth'
>>> turtle.right(120)
>>> turtle.forward(100)
>>> turtle.undo()
>>> turtle.pendown()
>>> turtle.forward(120)
>>> turtle.back(60)
>>> turtle.left(30)
>>> turtle.left(30)
>>> turtle.forward(60)
>>> turtle.penup()
>>> turtle.goto(0,0)
>>> turtle.pendown()
>>> turtle,right(30)
Traceback (most recent call last):
  File "<pyshell#158>", line 1, in <module>
    turtle,right(30)
NameError: name 'right' is not defined
>>> turtle.right(30)
>>> turtle.circule(20)
Traceback (most recent call last):
  File "<pyshell#160>", line 1, in <module>
    turtle.circule(20)
AttributeError: module 'turtle' has no attribute 'circule'
>>> turtle.circlee(20)
Traceback (most recent call last):
  File "<pyshell#161>", line 1, in <module>
    turtle.circlee(20)
AttributeError: module 'turtle' has no attribute 'circlee'
>>> turtle.circle(20)
>>> turtle.penup()
>>> turtle.goto(0, 50)
>>> turtle.goto(50, 100)
>>> turtle.pendown()
>>> turtle.forward(60)
>>> turtle.back(120)
>>> turtle.forward(60)
>>> turtle.left(90)
>>> turtle.forward(30)
>>> turtle.forward(30)
>>> turtle.penup()
>>> turtle.goto(100, 150)
>>> turtle.goto(190, 100)
>>> turtle.goto(210, 130)
>>> turtle.pendown()
>>> turtle.right(90)
>>> turtle.circle(40)
>>> turtle.penup()
>>> turtle.goto(240, 100)
>>> turtle.goto(250, 80)
>>> turtle.goto(250, 50)
>>> turtle.goto(260, 50)
>>> turtle.pendown()
>>> turtle.left(90)
>>> turtle.forward(60)
>>> turtle.back(120)
>>> turtle.forward(50)
>>> turtle.forward(20)
>>> turtle.back(10)
>>> turtle.right(90)
>>> turtle.forward(80)
>>>turtle.exitonclick()
